import { build } from "esbuild";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

const OUT = "dist";
const FEES = "research/fees.json";
const GENERATED = "src/generated/fee-tier.ts";

/**
 * Turn research/fees.json into a typed module. This is the only path by which a
 * fee rate reaches src/ — nothing here invents a number. If the research file
 * is absent or incomplete the module exports null and the extension renders
 * nothing (PROMPT.md rule 2.5) rather than shipping a guess (rule 0.2).
 */
async function generateFeeTier() {
  await mkdir("src/generated", { recursive: true });

  const blocked = async (why) => {
    await writeFile(
      GENERATED,
      `// GENERATED by build.mjs — do not edit.\n` +
        `// BLOCKED ON R2: ${why}\n` +
        `import type { FeeTier } from "../lib/types.js";\n` +
        `export const FEE_TIER_FROM_RESEARCH: FeeTier | null = null;\n`,
    );
    console.warn(`[build] fee tier unavailable — ${why}`);
  };

  if (!existsSync(FEES)) {
    await blocked(`${FEES} does not exist yet`);
    return;
  }

  let parsed;
  try {
    parsed = JSON.parse(await readFile(FEES, "utf8"));
  } catch (e) {
    await blocked(`${FEES} is not valid JSON: ${e.message}`);
    return;
  }

  const missing = ["takerRate", "makerRate", "source", "capturedAt"].filter(
    (k) => parsed[k] === undefined || parsed[k] === null || parsed[k] === "",
  );
  if (missing.length) {
    await blocked(`${FEES} is missing: ${missing.join(", ")}`);
    return;
  }
  if (typeof parsed.takerRate !== "number" || typeof parsed.makerRate !== "number") {
    await blocked(`${FEES} rates must be numbers`);
    return;
  }

  await writeFile(
    GENERATED,
    `// GENERATED by build.mjs from ${FEES} — do not edit.\n` +
      `// source: ${parsed.source}\n` +
      `// capturedAt: ${parsed.capturedAt}\n` +
      `import type { FeeTier } from "../lib/types.js";\n` +
      `export const FEE_TIER_FROM_RESEARCH: FeeTier | null = ${JSON.stringify(
        {
          takerRate: parsed.takerRate,
          makerRate: parsed.makerRate,
          source: parsed.source,
          capturedAt: parsed.capturedAt,
        },
        null,
        2,
      )};\n`,
  );
  console.log(`[build] fee tier generated from ${FEES} (captured ${parsed.capturedAt})`);
}

await generateFeeTier();

await build({
  entryPoints: {
    background: "src/background/index.ts",
    content: "src/content/index.ts",
  },
  bundle: true,
  format: "esm",
  target: "chrome120",
  outdir: OUT,
  sourcemap: true,
  logLevel: "info",
});

await copyFile("src/manifest.json", `${OUT}/manifest.json`);
console.log(`[build] wrote ${OUT}/ — load unpacked from there`);
